# Word embedding

In [1]:
import numpy as np

In [2]:
corpus = 'A corpus may contain texts in a single language (monolingual corpus) or text data in multiple languages (multilingual corpus). Multilingual corpora that have been specially formatted for side-by-side comparison are called aligned parallel corpora. There are two main types of parallel corpora which contain texts in two languages. In a translation corpus, the texts in one language are translations of texts in the other language. In a comparable corpus, the texts are of the same kind and cover the same content, but they are not translations of each other. To exploit a parallel text, some kind of text alignment identifying equivalent text segments (phrases or sentences) is a prerequisite for analysis. Machine translation algorithms for translating between two languages are often trained using parallel fragments comprising a first language corpus and a second language corpus which is an element-for-element translation of the first language corpus. In order to make the corpora more useful for doing linguistic research, they are often subjected to a process known as annotation. An example of annotating a corpus is part-of-speech tagging, or POS-tagging, in which information about each word\'s part of speech (verb, noun, adjective, etc.) is added to the corpus in the form of tags. Another example is indicating the lemma (base) form of each word. When the language of the corpus is not a working language of the researchers who use it, interlinear glossing is used to make the annotation bilingual.'
example_sentece = 'The quick brown fox jumps over the lazy dog'

## 1. Tokenization
Tokenization is the process when the input text (corpus) is splitted into smaller parts, called tokens. Token and word have often similar meaning, but not necessarily.

#### For example (the text in the parenthesis is one token):

* The quick brown fox jumps over the lazy dog.  

will be converted to:

* (The), (quick), (brown), (fox), (jumps), (over), (the), (lazy), (dog)  

#### But is some case it is not completely clear:

* It's not clear.
can be:
* (It's), (not), (clear)   
* (It), (s), (not), (clear)   
* (It), ('s), (not), (clear)  

We will implement a tokenization when we split text an all non alphanumeric characters!
So we pick:

* (It), (s), (not), (clear)


## Let's implement a tokenizer!  
### Help:  
#### get_non_alphanumeric_chars  
1. with the list() function it is easy to convert the input to list of characters   
2. with the .isalnum() function you can filter out all the non alphanumeric characters   
3. list(set(duplicated_list)) will keep only unique values in the list   

#### tokenizer
1. replace all non alphanumeric characters to whitespace! Use .replace() function.   
2. do the splitting via the .split() function

In [3]:
#GRADED function
#Don't change the function name, parameters and return values
def get_non_alphanumeric_chars(input_text):
    """
        Returns the non alphanumeric unique characters from a corpus.
        Input: 
            * input_text:   string
        Output:
            * non_alphanumeric_unique: list of non alphanumeric characters
    """     
    ###Start code here
    
    #STEP1 set character_list variable to a list of characters in the input_text 
    character_list = list(input_text)
    
    #STEP2 store all non_alphanumeric characters from the character_list!
    non_alphanumeric = []
    for i in character_list:
        if i.isalnum() == False:
            non_alphanumeric.append(i)
    
    #STEP3 keep only the unique characters (hint: unique_values = list(set(duplicated_values))
    non_alphanumeric_unique = list(set(non_alphanumeric))
    
    ###End code here 
    
    return non_alphanumeric_unique

In [4]:
print(get_non_alphanumeric_chars(corpus))
print(get_non_alphanumeric_chars('bla$$=()/ma z'))

[' ', '.', "'", '-', '(', ')', ',']
['/', ' ', '$', '=', '(', ')']


#### Expected output (maybe you will have different order but that is fine):

         ['.', ',', '-', "'", '(', ' ', ')']  
         ['/', '=', ' ', '(', '$', ')']

In [5]:
#GRADED function
#Don't change the function name, parameters and return values
def tokenizer(input_text):
    """
        Transforms strings to tokens. The tokens should appear in the same order as they are in the string.
        Input: 
            * input_text:   string
        Output:
            * tokens: list of tokens
    """    

    
    ###Start code here
    #STEP0 extract non alphanumeric characters! Use your function above!
    non_alphanumeric_unique = get_non_alphanumeric_chars(input_text)
    
    #STEP1 replace all non alphanumeric characters to ' ' whitespace.
    #replaced_input = None 
    
    for i in non_alphanumeric_unique:
        input_text=input_text.replace(str(i) , " ")
        
    replaced_input = input_text
    
    #STEP2 split the input_text on all the non_alphanumeric_unique characters and store then in the tokens variable
    tokens = replaced_input.split()
    
    ###End code here    
    
    
    return tokens

In [6]:
print(tokenizer(corpus[49:153]))
print()
print(tokenizer('Hi! How are you? I\'m fine, thanks... Bye'))

['monolingual', 'corpus', 'or', 'text', 'data', 'in', 'multiple', 'languages', 'multilingual', 'corpus', 'Multilingual', 'corpora', 'that']

['Hi', 'How', 'are', 'you', 'I', 'm', 'fine', 'thanks', 'Bye']


#### Expected output:

   ['monolingual', 'corpus', 'or', 'text', 'data', 'in', 'multiple', 'languages', 'multilingual', 'corpus', 'Multilingual',        'corpora', 'that']

   ['Hi', 'How', 'are', 'you', 'I', 'm', 'fine', 'thanks', 'Bye']

## 2. Stemming
This is the process when the inflected words are converted to their root word.

For example: goes $\to$ go, stemming $\to$ stem, fishing $\to$ fish

This can help a lot when the corpus is not large enough because then we do not have that many occurence of a word. And having just an s at the end of the word means a completely different word as we will see below.

It is not that easy to write a proper stemmer, so we will skip this part in the homework.

## 3. Dictionary & one-hot encoding
When the tokenization is ready we can build up a dictionary of the tokens. This is simply the sorted version of the tokens.

A dictionary looks like: ['a', 'an', 'apple', ..., 'orange', ..., 'zebra', 'zulu']

From now we can think of a word as a vector which has 1 at the position of the word in the dictionary, and 0-s anywhere else.

$a = \begin{bmatrix}
           1 \\
           0 \\
           0 \\
           \vdots \\
           0 \\
           0
         \end{bmatrix},\:\:$  $an = \begin{bmatrix}
           0 \\
           1 \\
           0 \\
           \vdots \\
           0 \\
           0
         \end{bmatrix},\:\:$ $apple = \begin{bmatrix}
           0 \\
           0 \\
           1 \\
           \vdots \\
           0 \\
           0
         \end{bmatrix}\:\: ... \:\:$ $zebra = \begin{bmatrix}
           0 \\
           0 \\
           0 \\
           \vdots \\
           1 \\
           0
         \end{bmatrix},\:\:$ $zulu = \begin{bmatrix}
           0 \\
           0 \\
           0 \\
           \vdots \\
           0 \\
           1
         \end{bmatrix}$

## Let's build a dictionary and the one-hot encoding!

In [7]:
#GRADED function
#Don't change the function name, parameters and return values
def get_dictionary(input_text):
    """
        Builds up the dictionary from an input text.
        Input: 
            * input_text:   string
        Output:
            * dictionary: list of unique, sorted tokens
    """    
    tokens = tokenizer(input_text)
    
    ###Start code here
    
    unique_tokens = list(set(tokens))
    unique_sorted_tokens = sorted(unique_tokens)
    
    ###End code here
    dictionary = unique_sorted_tokens

    return dictionary

In [8]:
print(get_dictionary(corpus.lower())[0:10])
print(len(get_dictionary(corpus.lower())))

['a', 'about', 'added', 'adjective', 'algorithms', 'aligned', 'alignment', 'an', 'analysis', 'and']
118


#### Expected output:

         ['a', 'about', 'added', 'adjective', 'algorithms', 'aligned', 'alignment', 'an', 'analysis', 'and']  
         118

In [9]:
#GRADED function
#Don't change the function name, parameters and return values
def one_hot_encoded(word, dictionary):
    """
        Turn a word to a one-hot encoded vector based on the dictionary.
        Input: 
            * word:   string
            * dictionary: list of words in a dictionary
        Output:
            * oh_vec: one-hot encoded vector
    """    
    #check if word is in dictionary
    if(not word in dictionary):
        print('The word _' + word + '_ is not in dictionary!')
        return None
    
    ###Start code here
    # oh_vec should be a numpy array with a shape (len(dictionary), 1)
    # it should contains 0 everywhere except for the position of the word in the dictionary. There is should be 1. 
    
    a=[]
    for i in range(len(dictionary)):
        if word == dictionary[i]:
            a.append(1)
        else:
            a.append(0)
    b=np.array(a)
    oh_vec=b.reshape(len(dictionary),1)
    
    ###End code here

    return oh_vec

In [10]:
dic = get_dictionary(corpus.lower())

print(one_hot_encoded('a', dic)[0:10])
print()
print(one_hot_encoded('aligned', dic)[0:10])
print()
print(one_hot_encoded('ablak', dic))

[[1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]

[[0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]]

The word _ablak_ is not in dictionary!
None


#### Expected output:

[[1]  
 [0]  
 [0]  
 [0]  
 [0]  
 [0]  
 [0]  
 [0]  
 [0]   
 [0]]   

[[0]   
 [0]   
 [0]   
 [0]   
 [0]   
 [1]   
 [0]   
 [0]   
 [0]   
 [0]]   

The word \_ablak_ is not in dictionary!     
None

## 4. Continuous bag of words (CBOW) concept
In the CBOW model we try to fit a model that can predict a word by it's neighbors. We expect that if we manage to fit such a model, the inner representation of the model will capture the meaning of the different words.

The number of neighbors is a parameter, for 4 neighbors it looks like (the red is the target word, the blue words are the input, the neighbors):    
over the lazy dog    
The the lazy dog        
The quick lazy dog     
The quick brown dog  

As it can be seen above from a sentence it is easy to create many training examples!

#### Let's make a CBOW example generator!

In [11]:
#GRADED function
#Don't change the function name, parameters and return values
def generate_CBOW_example(start_pos, half_window, tokens):
    """
        Generated CBOW training examples from tokens
        Input: 
            * start_pos:   the position of the first example
            * half_window: number of tokens on one-side
            * tokens: list of tokens
        Output:
            * X: input words (the neighbors)
            * Y: target word
    """     
    
    ###Start code here
    
    Y = tokens[start_pos+half_window]
    X = []
    print(start_pos)
    for i in range(0, 0+2*half_window+1):
        if i != (half_window):
            X.append(tokens[start_pos+i])
    
    ###End code here
    
    return X, Y

In [12]:
corpus_tokens = tokenizer(corpus.lower())

print(generate_CBOW_example(0, 2, corpus_tokens))
print(generate_CBOW_example(2, 2, corpus_tokens))
print(generate_CBOW_example(0, 3, corpus_tokens))

0
(['a', 'corpus', 'contain', 'texts'], 'may')
2
(['may', 'contain', 'in', 'a'], 'texts')
0
(['a', 'corpus', 'may', 'texts', 'in', 'a'], 'contain')


#### Expected output:

            (['a', 'corpus', 'contain', 'texts'], 'may')   
            (['may', 'contain', 'in', 'a'], 'texts')    
            (['a', 'corpus', 'may', 'texts', 'in', 'a'], 'contain')      

## 5. Skip-gram concept
Skip-gram is the opposite of the CBOW. Now starting from a single word we want to predict it's neighbors.

In the skip-gram model we try to fit a model that can predict a word's neighbors. We expect that if we manage to fit such a model, the inner representation of the model will capture the meaning of the different words.

The number of neighbors is a parameter, for 4 neighbors it looks like (the blue are the target words, the red word is the input):    
over the lazy dog      
The the lazy dog       
The quick lazy dog      
The quick brown dog       

As it can be seen above from a sentence it is easy to create many training examples!

#### Let's make a skip-gram example generator!
        
#### Luckily it is very easy now. We only need to change X and Y in the CBOW generator.

In [13]:
def generate_skip_gram_example(start_pos, half_window, tokens):
    """
        Generated skip-gram training examples from tokens
        Input: 
            * start_pos:   the position of the first example
            * half_window: number of tokens on one-side
            * tokens: list of tokens
        Output:
            * x: input word
            * y: target words
    """     
    
    X, Y = generate_CBOW_example(start_pos, half_window, tokens)
    x = Y
    y = X
    return x, y

## 6. Keras models
Skip-gram is said to word better for smaller amount of training data and for rare words, but CBOW is faster to train and said to be better for frequent words.

If we have a corpus with $N$ tokens then we will have $N$ training examples for CBOW and $\approx window\_size \cdot N$ training examples for skip-gram.

Training these models can be really slow so a few other tricks are used for training. For the simplicity we won't implement them now.

### 6.1 CBOW model
In the model we take a training example which contains $N$ input words and a target word.

![title](cbow.png)

The model is the following:

1. convert the $N$ input words to one-hot encoded ($V$ long) vectors and average them!
2. add a hidden layer of $d$ neurons (no activation, no bias, just the matrix multiplication)
3. add an output layer with $V$ neurons (no bias) and softmax activation.

In [14]:
from keras.layers import Dense
from keras.models import Sequential

Using TensorFlow backend.


In [15]:
#GRADED function
#Don't change the function name, parameters and return values
def get_keras_cbow(hidden_dim, dictionary_size):
    """
        Generate keras model for CBOW model
        Input: 
            * hidden_dim: number of nurons in the hidden layer
            * dictionary_size: length of the dictionary (output/input size)
        Output:
            * model: keras model that implements CBOW 
    """
    cbow = Sequential()
    ###Start code here
    
    # add a Dense layer with hidden_dim neurons. Input_dim is the dictionary_size 
    # we don't need nor activation neither bias!
    cbow.add(Dense(units=hidden_dim, use_bias=False, input_dim=dictionary_size))
    
    # add a Dense layer with dictionary_size neurons. We don't need bias. Activation is softmax.
    cbow.add(Dense(dictionary_size, use_bias=False, activation='softmax'))
    
    ###End code here
    
    return cbow

#### Let's train it on out toy corpus. We should see the loss decreasing, but we do not expect anything serious.

In [16]:
dic = get_dictionary(corpus.lower())
cbow_model = get_keras_cbow(30, len(dic))
cbow_model.compile(optimizer='adam', loss='categorical_crossentropy')

In [17]:
epochs = 10
half_window = 2
corpus_tokens = tokenizer(corpus.lower())
max_pos_start = len(corpus_tokens)-2*half_window

for iteration in range(epochs): #iterate the corpus epochs times
    loss = 0.
    
    for pos_start in range(max_pos_start): # iterate on the token positions
        x, y = generate_CBOW_example(pos_start, half_window, corpus_tokens) # generate training examples
        
        x = np.array([one_hot_encoded(i, dic) for i in x]).sum(0).T 
        y = one_hot_encoded(y, dic).T
        
        loss += cbow_model.train_on_batch(x, y) # train the model. only 1 sample/batch now...

    print('Epoch', str(iteration+1).zfill(2), ', Loss:',  loss/(max_pos_start))

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
Epoch 01 , Loss: 4.781901820632052
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38


You should see the loss decreasing.

### 6.2 skip-gram model
In the model we take a training example which contains an input word and the $N$ target words. We will handle the target words separately, so actually it means $N$ different training X-Y pairs.

![title](skip_gram.png)

The model is the following:

1. convert the input word and one of the target word to one-hot encoded ($V$ long) vector!
2. add a hidden layer of $d$ neurons (no activation, no bias, just the matrix multiplication)
3. add an output layer with $V$ neurons (no bias) and softmax activation.  

Luckily it is exactly the same model than the CBOW. The only difference is how we create the input and the target.

In [18]:
dic = get_dictionary(corpus.lower())
skip_gram_model = get_keras_cbow(30, len(dic))
skip_gram_model.compile(optimizer='adam', loss='categorical_crossentropy')

In [19]:
epochs = 10
half_window = 2
corpus_tokens = tokenizer(corpus.lower())
max_pos_start = len(corpus_tokens)-2*half_window

for iteration in range(epochs): #iterate the corpus epochs times
    loss = 0.
    
    for pos_start in range(max_pos_start): # iterate on the token positions
        x, y = generate_skip_gram_example(pos_start, half_window, corpus_tokens) # generate training examples
        
        x = one_hot_encoded(x, dic).T  
        y = np.array([one_hot_encoded(i, dic) for i in y])
        
        for i in y: # iterate on the target words
            loss += skip_gram_model.train_on_batch(x, i.T) # train the model. only 1 sample/batch now...

    print('Epoch', str(iteration+1).zfill(2), ', Loss:',  loss/(max_pos_start*len(y)))

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
Epoch 01 , Loss: 4.755243241294356
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38


You should see the loss decreasing.

#### This is the end of the homework. The deadline is 2018.04.24.   

In the next homework we will continue to our smiley generator!